version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: p255w0rd
      MYSQL_USER: tushar
      MYSQL_PASSWORD: p255w0rd
      MYSQL_DATABASE: text_to_video
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - text-to-video-network

  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - text-to-video-network

  backend:
    build: ./backend
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: text_to_video
      DB_USER: tushar
      DB_PASSWORD: p255w0rd
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      PORT: 8080
    volumes:
      - videos_data:/root/videos
    depends_on:
      - mysql
      - redis
    networks:
      - text-to-video-network

  video-service:
    build: ./video-service
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: text_to_video
      DB_USER: tushar
      DB_PASSWORD: p255w0rd
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      PORT: 8000
    volumes:
      - videos_data:/app/videos
    depends_on:
      - mysql
      - redis
    networks:
      - text-to-video-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]

  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend
    networks:
      - text-to-video-network

volumes:
  mysql_data:
  redis_data:
  videos_data:

networks:
  text-to-video-network:
    driver: bridge 
