apiVersion: v1
kind: Secret
metadata:
  name: text-to-video-secret
  namespace: text-to-video
type: Opaque
data:
  DB_USER: dHVzaGFy
  DB_PASSWORD: cDI1NXcwcmQ=
  REDIS_PASSWORD: ""  # empty for no password