apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
  namespace: text-to-video
spec:
  restartPolicy: Never
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.present
            operator: In
            values:
            - "true"
          - key: kubernetes.io/hostname
            operator: In
            values:
            - g230
  containers:
  - name: nvidia-smi
    image: nvidia/cuda:12.3.2-base-ubuntu22.04
    command: ["nvidia-smi"]
    resources:
      limits:
        nvidia.com/gpu: 2